"""土壤检测档案与施肥作业接口测试。"""

from datetime import date


def soil_payload(space_id, **overrides):
    payload = {
        "green_space_id": space_id,
        "sample_date": "2026-03-01",
        "sample_point": "中央草坪 5 点混合样",
        "sample_depth": 20,
        "lab_org": "市园林科学研究所检测中心",
        "report_no": "TR-2026-0312",
        "soil_texture": "loam",
        "ph_value": 6.8,
        "organic_matter": 18.5,
        "alkali_nitrogen": 86.0,
        "available_phosphorus": 12.4,
        "available_potassium": 132.0,
        "bulk_density": 1.32,
        "moisture": 22.5,
        "target_plants": "马尼拉草坪、金森女贞",
    }
    payload.update(overrides)
    return payload


# ---------------------------------------------------------------- 检测档案
def test_create_soil_test_generates_code_and_grades(api, make_space):
    space = make_space()
    data = api.data(api.post("/api/v1/soil-tests", soil_payload(space.id)), 201)
    assert data["test_no"].startswith("ST-")
    assert data["ph_value"] == 6.8
    assert data["ph_level"] == "neutral"
    assert data["ph_level_label"] == "中性"
    assert data["organic_level"] == "low"
    assert data["nitrogen_level"] == "low"
    assert data["phosphorus_level"] == "low"
    assert data["potassium_level"] == "medium"
    assert data["soil_texture_label"] == "壤土"


def test_strong_acid_and_nutrient_lack_are_graded(api, make_space):
    space = make_space()
    data = api.data(api.post("/api/v1/soil-tests", soil_payload(
        space.id, ph_value=4.6, organic_matter=0.8,
        alkali_nitrogen=40, available_phosphorus=3, available_potassium=40,
    )), 201)
    assert data["ph_level"] == "strong_acid"
    assert data["organic_level"] == "very_low"
    assert data["nitrogen_level"] == "lack"
    assert data["phosphorus_level"] == "lack"
    assert data["potassium_level"] == "lack"


def test_required_and_range_validation(api, make_space):
    space = make_space()
    response = api.post("/api/v1/soil-tests", soil_payload(
        space.id, sample_point="", lab_org="",
        ph_value=15, organic_matter=-1,
        alkali_nitrogen=None, available_phosphorus=None, available_potassium=None,
    ))
    assert response.status_code == 422
    details = response.get_json()["data"]
    assert set(details) >= {
        "sample_point", "lab_org", "ph_value", "organic_matter",
        "alkali_nitrogen", "available_phosphorus", "available_potassium",
    }


def test_sample_date_cannot_precede_established_date(api, make_space):
    space = make_space(established_date=date(2020, 1, 1))
    response = api.post("/api/v1/soil-tests", soil_payload(space.id, sample_date="2019-01-01"))
    assert response.status_code == 422
    assert "采样日期" in response.get_json()["data"]["sample_date"]


def test_custom_formula_is_kept_and_missing_formula_autogenerated(api, make_space):
    space = make_space(green_type="road")

    # 不提供配方 -> 系统按缺素与绿地类型自动生成
    auto = api.data(api.post("/api/v1/soil-tests", soil_payload(space.id)), 201)
    assert auto["fertilizer_type"]
    assert auto["fertilizer_name"]
    assert auto["dosage_per_sqm"] > 0
    assert auto["application_method_label"]
    assert "施肥" in auto["formula_advice"]

    # 手工提供配方 -> 原样保留
    custom = api.data(api.post("/api/v1/soil-tests", soil_payload(
        space.id, report_no="TR-CUSTOM", fertilizer_type="organic",
        fertilizer_name="腐熟羊粪", nutrient_ratio="有机质≥45%",
        dosage_per_sqm=2.0, application_frequency="每年 1 次",
        application_method="broadcast", application_period="秋季",
        formula_advice="结合秋施基肥改土",
    )), 201)
    assert custom["fertilizer_type"] == "organic"
    assert custom["fertilizer_name"] == "腐熟羊粪"
    assert custom["dosage_per_sqm"] == 2.0
    assert custom["formula_advice"] == "结合秋施基肥改土"


def test_regenerate_plan_overwrites_formula(api, make_space):
    space = make_space()
    created = api.data(api.post("/api/v1/soil-tests", soil_payload(
        space.id, fertilizer_type="organic", fertilizer_name="自定义肥料",
    )), 201)
    assert created["fertilizer_name"] == "自定义肥料"

    regenerated = api.data(api.post(f"/api/v1/soil-tests/{created['id']}/regenerate-plan"))
    assert regenerated["fertilizer_type"]
    assert regenerated["fertilizer_name"] != "自定义肥料"


def test_list_filter_and_summary(api, make_space):
    space = make_space()
    other = make_space(name="其他绿地")
    api.post("/api/v1/soil-tests", soil_payload(space.id, ph_value=4.8))
    api.post("/api/v1/soil-tests", soil_payload(space.id, sample_date="2026-05-01",
                                                report_no="TR-2", ph_value=7.2))
    api.post("/api/v1/soil-tests", soil_payload(other.id, report_no="TR-3"))

    data = api.data(api.get("/api/v1/soil-tests", green_space_id=space.id))
    assert data["meta"]["total"] == 2

    data = api.data(api.get("/api/v1/soil-tests", ph_level="strong_acid"))
    assert data["meta"]["total"] == 1

    summary = api.data(api.get("/api/v1/soil-tests/summary"))
    assert summary["total_count"] == 3
    assert summary["green_space_count"] == 2
    assert summary["abnormal_ph_count"] == 1


def test_comparison_returns_history_in_date_order(api, make_space):
    space = make_space()
    api.post("/api/v1/soil-tests", soil_payload(space.id, sample_date="2026-03-01",
                                                ph_value=5.6, organic_matter=15.0))
    api.post("/api/v1/soil-tests", soil_payload(space.id, sample_date="2026-09-01",
                                                report_no="TR-2", ph_value=6.9, organic_matter=26.0))

    data = api.data(api.get("/api/v1/soil-tests/comparison", green_space_id=space.id))
    assert data["green_space"]["id"] == space.id
    assert [item["sample_date"] for item in data["items"]] == ["2026-03-01", "2026-09-01"]
    assert [item["ph_value"] for item in data["items"]] == [5.6, 6.9]
    assert [item["organic_matter"] for item in data["items"]] == [15.0, 26.0]


def test_comparison_requires_green_space(api):
    response = api.get("/api/v1/soil-tests/comparison")
    assert response.status_code == 422


def test_delete_soil_test(api, make_soil_test):
    test = make_soil_test()
    api.delete(f"/api/v1/soil-tests/{test.id}")
    assert api.get(f"/api/v1/soil-tests/{test.id}").status_code == 404


# ---------------------------------------------------------------- 施肥作业
def test_create_application_inherits_formula(api, make_soil_test):
    test = make_soil_test()
    data = api.data(api.post("/api/v1/fertilizations", {
        "soil_test_id": test.id,
        "plan_date": "2026-03-20",
        "planned_area": 2000,
        "executor": "绿化二班",
    }), 201)
    assert data["application_no"].startswith("FA-")
    assert data["green_space_id"] == test.green_space_id
    assert data["fertilizer_name"] == test.fertilizer_name
    # 建议用量 0.05kg/㎡（park 默认）× 2000㎡
    assert data["planned_dosage"] == float(test.dosage_per_sqm)
    assert data["planned_amount"] == round(2000 * float(test.dosage_per_sqm), 2)
    assert data["status"] == "planned"
    assert data["status_label"] == "待执行"


def test_application_rejects_unknown_test(api):
    response = api.post("/api/v1/fertilizations", {
        "soil_test_id": 99999, "plan_date": "2026-03-20",
    })
    assert response.status_code == 422
    assert "不存在" in response.get_json()["data"]["soil_test_id"]


def test_application_date_cannot_precede_sample(api, make_soil_test):
    test = make_soil_test(sample_date=date(2026, 3, 1))
    response = api.post("/api/v1/fertilizations", {
        "soil_test_id": test.id, "plan_date": "2026-02-01",
    })
    assert response.status_code == 422
    assert "采样日期" in response.get_json()["data"]["plan_date"]


def test_backfill_actual_amount_computes_deviation(api, make_fertilization):
    application = make_fertilization(planned_area=2000)
    planned = float(application.planned_amount)

    data = api.data(api.put(f"/api/v1/fertilizations/{application.id}", {
        "soil_test_id": application.soil_test_id,
        "plan_date": "2026-03-20",
        "planned_area": 2000,
        "status": "applied",
        "applied_date": "2026-03-21",
        "actual_dosage": 0.06,
        "actual_area": 2000,
        "worker": "王海涛",
        "work_hours": 8,
    }))
    assert data["status"] == "applied"
    assert data["actual_amount"] == 120.0
    assert data["deviation"] == round(120.0 - planned, 2)

    # 检测档案详情能看到回填的施肥作业与累计实际用量
    detail = api.data(api.get(f"/api/v1/soil-tests/{application.soil_test_id}"))
    assert detail["application_count"] == 1
    assert detail["total_applied_amount"] == 120.0
    assert detail["applications"][0]["actual_amount"] == 120.0


def test_fertilization_summary_and_filters(api, make_fertilization):
    applied = make_fertilization(planned_area=1000, status="applied",
                                 applied_date=date(2026, 3, 22),
                                 actual_dosage=0.06, actual_area=1000)
    make_fertilization(planned_area=500)

    summary = api.data(api.get("/api/v1/fertilizations/summary"))
    assert summary["total_count"] == 2
    assert summary["applied_count"] == 1
    assert summary["planned_count"] == 1
    assert summary["actual_amount"] == 60.0

    data = api.data(api.get("/api/v1/fertilizations", status="applied"))
    assert data["meta"]["total"] == 1
    assert data["items"][0]["id"] == applied.id


def test_deleting_soil_test_cascades_applications(api, make_fertilization):
    application = make_fertilization()
    test_id = application.soil_test_id
    api.delete(f"/api/v1/soil-tests/{test_id}")
    assert api.get(f"/api/v1/fertilizations/{application.id}").status_code == 404


def test_deleting_green_space_blocks_with_soil_test(api, make_soil_test):
    test = make_soil_test()
    space_id = test.green_space_id

    response = api.delete(f"/api/v1/green-spaces/{space_id}")
    assert response.status_code == 409
    assert response.get_json()["data"]["soil_test"] == 1

    api.delete(f"/api/v1/green-spaces/{space_id}", force="true")
    assert api.get(f"/api/v1/soil-tests/{test.id}").status_code == 404


# ---------------------------------------------------------------- 绿地档案
def test_green_space_profile_includes_soil_tests(api, make_soil_test):
    test = make_soil_test(ph_value=5.8)
    space_id = test.green_space_id

    profile = api.data(api.get(f"/api/v1/green-spaces/{space_id}/profile"))
    assert profile["soil_test_count"] == 1
    assert profile["latest_soil_test"]["ph_value"] == 5.8
    assert profile["recent_soil_tests"][0]["test_no"] == test.test_no


def test_green_space_listing_counts_soil_tests(api, make_soil_test):
    test = make_soil_test()
    data = api.data(api.get("/api/v1/green-spaces"))
    row = next(item for item in data["items"] if item["id"] == test.green_space_id)
    assert row["statistics"]["soil_test_count"] == 1
